language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - redis-server

install:
  - pip install .
  - pip install coverage

script:
  - nosetests --with-coverage --cover-package=school_api

after_success:
  - pip install codecov
  - codecov
